from src.visualization.plots import render_image
from src.visualization.heatmaps import build_damage_heatmap_overlay, build_ocr_confidence_map
from src.visualization.comparison import build_comparison_grid, build_stage_slider_data